services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:ratestask@db:5432/ratestask
    depends_on:
      - db

  db:
    image: panchami34/ratestask
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ratestask
      POSTGRES_DB: ratestask

  test:
    build: .
    command: pytest
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/ratestask
      - PYTHONPATH=. pytest
    depends_on:
      - db